// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pojwuoswhmcjaofhpogr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvand1b3N3aG1jamFvZmhwb2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjE3ODgsImV4cCI6MjA2NTQ5Nzc4OH0.ccqIbcwib-nW6AtOV3AkpFfHxmWOBSfxInjN2Daq5C8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);